### PR TITLE
3.2.0 Release

### PR DESCRIPTION
**Pull request by nblumhardt**
* #146 - `EnrichDiagnosticContext` (@tomkerkhove)
 * #149 - fix collection of properties in `EnrichDiagnosticContext` (@alastair-gatpark)

### CODE REVIEW

**Comment by D9001** [comment]
I just pulled down 3.2.0 and had to downgrade back to a dev version in order to use the properties in the docs 😥 
At the very least, could you hold off on updating the readme with these methods until they're available in the stable release? I found your blogs very helpful and informative but was really confused when I couldn't find these methods even though they were in the docs.

**Comment by nblumhardt** [comment]
Hi! Do you mean you pulled down 3.1.0? Version 3.2.0 is out now and includes everything that's in the README.

Unfortunately GitHub conflates the default branch for PRs (which needs to be `dev`, or else we have to field a whole lot of misdirected effort when people accidentally code PRs against the older code in `master`), and the branch from which README is shown.

In future my plan's to tag pre-release features in the README - tried that recently with <sup>3.0.0-*</sup> to some degree of success, should have done the same for `EnrichDiagnosticContext` - sorry about the confusion.

In any case, grabbing the latest from NuGet now should have you sorted :-)

**Comment by D9001** [comment]
That makes sense (about the readme). Thank you!
When I pull 3.2.0, `EnrichDiagnosticContext` appears unavailable until I switch to 3.2.0-devxxx or even 3.1.1-devxx. It's very strange.

**Comment by D9001** [comment]
Update: 

I can't make any sense of it, but all of a sudden each project I have that tries to make use of `UseSerilogRequestLogging` is unable to run because of this error on StartUp. I only noticed once my CI/CD pipeline failed because it had worked fine when I was using the dev version. Is there anything I can do on my end to fix the missing dependencies within my project or is this likely a larger issue? If so, I can make an official issue to track it. 

```
System.InvalidOperationException: Unable to resolve service for type 'Serilog.Extensions.Hosting.DiagnosticContext' while attempting to activate 'Serilog.AspNetCore.RequestLoggingMiddleware'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
```

**Pull request merged**
